/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */
plugins {
    kotlin("jvm") version "1.6.21"
    id("io.gitlab.arturbosch.detekt") version "1.20.0"
}

repositories{
    mavenCentral()
}

dependencies{

}

detekt {
    buildUponDefaultConfig = true
    config = files(projectDir.resolve("detekt.yml"))
}
