/*
 * DO NOT EDIT THIS FILE - it is machine generated
 * from org.ksmt.solver.bitwuzla.bindings.Native.kt (javac -h)
*/
#include <jni.h>
/* Header for class org_ksmt_solver_bitwuzla_bindings_Native */

#ifndef _Included_org_ksmt_solver_bitwuzla_bindings_Native
#define _Included_org_ksmt_solver_bitwuzla_bindings_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaInit
 * Signature: ()J
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaInit
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermDecRef
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermDecRef
(JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortDecRef
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortDecRef
(JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaForceTerminate
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaForceTerminate
(JNIEnv* env, jobject native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaCopyright
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaCopyright
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaVersion
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGitId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGitId
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaOptionsNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaOptionsNew
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaOptionsDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaOptionsDelete
  (JNIEnv *env, jclass native_class, jlong);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaOptionIsNumeric
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaOptionIsNumeric
  (JNIEnv *env, jclass native_class, jlong options, jint option);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaOptionIsMode
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaOptionIsMode
  (JNIEnv *env, jclass native_class, jlong options, jint option);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSetOption
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSetOption
  (JNIEnv *env, jclass native_class, jlong options, jint option, jlong value);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSetOptionMode
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSetOptionMode
  (JNIEnv *env, jclass native_class, jlong options, jint option, jstring value);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetOption
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetOption
  (JNIEnv *env, jclass native_class, jlong options, jint option);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetOptionMode
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetOptionMode
  (JNIEnv *env, jclass native_class, jlong options, jint option);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortHash
 * Signature: (J)I
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortHash
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortBvGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortBvGetSize
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortFpGetExpSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortFpGetExpSize
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortFpGetSigSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortFpGetSigSize
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortArrayGetIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortArrayGetIndex
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortArrayGetElement
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortArrayGetElement
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortFunGetDomainSorts
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortFunGetDomainSorts
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortFunGetCodomain
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortFunGetCodomain
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortFunGetArity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortFunGetArity
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortGetUninterpretedSymbol
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortGetUninterpretedSymbol
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsEqual
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsEqual
  (JNIEnv *env, jclass native_class, jlong sort0, jlong sort1);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsArray
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsArray
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsBool
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsBv
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsBv
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsFp
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsFp
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsFun
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsFun
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsRm
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsRm
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortIsUninterpreted
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortIsUninterpreted
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSortToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSortToString
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermHash
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermHash
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermGetKindNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermGetKindNative
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermGetChildren
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermGetChildren
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermGetIndices
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermGetIndices
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsIndexed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsIndexed
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermGetSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermGetSort
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermArrayGetIndexSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermArrayGetIndexSort
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermArrayGetElementSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermArrayGetElementSort
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermFunGetDomainSorts
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermFunGetDomainSorts
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermFunGetCodomainSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermFunGetCodomainSort
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermBvGetSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermBvGetSize
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermFpGetExpSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermFpGetExpSize
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermFpGetSigSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermFpGetSigSize
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermFunGetArity
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermFunGetArity
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermGetSymbol
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermGetSymbol
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsEqualSort
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsEqualSort
  (JNIEnv *env, jclass native_class, jlong term0, jlong term1);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsArray
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsArray
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsConst
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsConst
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFun
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFun
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsVar
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsVar
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsValue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsValue
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValue
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValue
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValue
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBool
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBv
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBv
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFp
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFp
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRm
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRm
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsUninterpreted
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsUninterpreted
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsTrue
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsTrue
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFalse
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFalse
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValueZero
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValueZero
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValueOne
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValueOne
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValueOnes
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValueOnes
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValueMinSigned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValueMinSigned
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsBvValueMaxSigned
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsBvValueMaxSigned
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValuePosZero
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValuePosZero
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValueNegZero
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValueNegZero
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValuePosInf
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValuePosInf
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValueNegInf
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValueNegInf
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsFpValueNan
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsFpValueNan
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValueRna
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValueRna
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValueRne
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValueRne
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValueRtn
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValueRtn
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValueRtp
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValueRtp
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermIsRmValueRtz
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermIsRmValueRtz
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermValueGetBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermValueGetBool
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermValueGetStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermValueGetStr
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermValueGetStrFmt
 * Signature: (JB)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermValueGetStrFmt
  (JNIEnv *env, jclass native_class, jlong term, jbyte base);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermValueGetRm
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermValueGetRm
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermToString
  (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaTermToStringFmt
 * Signature: (JB)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaTermToStringFmt
  (JNIEnv *env, jclass native_class, jlong term, jbyte base);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaNew
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaNew
  (JNIEnv *env, jclass native_class, jlong options);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaDelete
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaPush
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaPush
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlong nlevels);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaPop
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaPop
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlong nlevels);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaAssert
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaAssert
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetAssertions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetAssertions
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaIsUnsatAssumption
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaIsUnsatAssumption
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetUnsatAssumptions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetUnsatAssumptions
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetUnsatCore
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetUnsatCore
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSimplify
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSimplify
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaCheckSatNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaCheckSatNative
  (JNIEnv *env, jclass native_class, jlong bitwuzla);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaCheckSatAssumingNative
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaCheckSatAssumingNative
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlongArray args);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaCheckSatTimeout
 * Signature: (J[JJ)I
 */
JNIEXPORT jint JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaCheckSatTimeout
  (JNIEnv* env, jobject native_class, jlong bitwuzla, jlongArray args, jlong timeout);


/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetValue
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetValue
  (JNIEnv *env, jclass native_class, jlong bitwuzla, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetBvValueUInt64
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetBvValueUInt64
        (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetBvValueString
 */
JNIEXPORT jstring JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetBvValueString
        (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaGetFpValue
 */
JNIEXPORT jobject JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaGetFpValue
        (JNIEnv *env, jclass native_class, jlong term);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkArraySort
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkArraySort
  (JNIEnv *env, jclass native_class, jlong index, jlong element);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBoolSort
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBoolSort
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvSort
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvSort
  (JNIEnv *env, jclass native_class, jlong size);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpSort
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpSort
  (JNIEnv *env, jclass native_class, jlong expSize, jlong sigSize);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFunSort
 * Signature: ([JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFunSort
  (JNIEnv *env, jclass native_class, jlongArray domain, jlong codomain);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkRmSort
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkRmSort
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkUninterpretedSort
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkUninterpretedSort
  (JNIEnv *env, jclass native_class, jstring symbol);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTrue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTrue
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFalse
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFalse
  (JNIEnv *env, jclass native_class);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvZero
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvZero
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvOne
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvOne
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvOnes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvOnes
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvMinSigned
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvMinSigned
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvMaxSigned
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvMaxSigned
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpPosZero
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpPosZero
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpNegZero
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpNegZero
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpPosInf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpPosInf
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpNegInf
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpNegInf
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpNan
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpNan
  (JNIEnv *env, jclass native_class, jlong sort);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvValue
 * Signature: (JLjava/lang/String;B)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvValue
  (JNIEnv *env, jclass native_class, jlong sort, jstring value, jbyte base);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvValueUint64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvValueUint64
  (JNIEnv *env, jclass native_class, jlong sort, jlong value);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkBvValueInt64
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkBvValueInt64
  (JNIEnv *env, jclass native_class, jlong sort, jlong value);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpValue
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpValue
  (JNIEnv *env, jclass native_class, jlong bvSign, jlong bvExponent, jlong bvSignificand);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpFromReal
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpFromReal
  (JNIEnv *env, jclass native_class, jlong sort, jlong rm, jstring real);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkFpFromRational
 * Signature: (JJLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkFpFromRational
  (JNIEnv *env, jclass native_class, jlong sort, jlong rm, jstring num, jstring den);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkRmValue
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkRmValue
  (JNIEnv *env, jclass native_class, jint rm);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm1
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm1
  (JNIEnv *env, jclass native_class, jint kind, jlong arg);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm2
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm2
  (JNIEnv *env, jclass native_class, jint kind, jlong arg0, jlong arg1);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm3
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm3
  (JNIEnv *env, jclass native_class, jint kind, jlong arg0, jlong arg1, jlong arg2);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm
 * Signature: (I[J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm
  (JNIEnv *env, jclass native_class, jint kind, jlongArray args);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm1Indexed1
 * Signature: (IJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm1Indexed1
  (JNIEnv *env, jclass native_class, jint kind, jlong arg, jlong idx);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm1Indexed2
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm1Indexed2
  (JNIEnv *env, jclass native_class, jint kind, jlong arg, jlong idx0, jlong idx1);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm2Indexed1
 * Signature: (IJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm2Indexed1
  (JNIEnv *env, jclass native_class, jint kind, jlong arg0, jlong arg1, jlong idx);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTerm2Indexed2
 * Signature: (IJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTerm2Indexed2
  (JNIEnv *env, jclass native_class, jint kind, jlong arg0, jlong arg1, jlong idx0, jlong idx1);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkTermIndexed
 * Signature: (I[J[J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkTermIndexed
  (JNIEnv *env, jclass native_class, jint kind, jlongArray args, jlongArray idxs);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkConst
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkConst
  (JNIEnv *env, jclass native_class, jlong sort, jstring symbol);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkConstArray
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkConstArray
  (JNIEnv *env, jclass native_class, jlong sort, jlong value);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaMkVar
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaMkVar
  (JNIEnv *env, jclass native_class, jlong sort, jstring symbol);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSubstituteTerm
 * Signature: (J[J[J)J
 */
JNIEXPORT jlong JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSubstituteTerm
  (JNIEnv *env, jclass native_class, jlong term, jlongArray mapKeys, jlongArray mapValues);

/*
 * Class:     org_ksmt_solver_bitwuzla_bindings_Native
 * Method:    bitwuzlaSubstituteTerms
 * Signature: ([J[J[J)V
 */
JNIEXPORT void JNICALL Java_org_ksmt_solver_bitwuzla_bindings_Native_bitwuzlaSubstituteTerms
  (JNIEnv *env, jclass native_class, jlongArray terms, jlongArray mapKeys, jlongArray mapValues);

#ifdef __cplusplus
}
#endif
#endif
