source 'https://rubygems.org'

gem 'jekyll', '~> 4.3', '>= 4.3.2'
gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem 'rake', '~> 11.2', '>= 11.2.2'