name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      - name: Build artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToReleaseDirRepository

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ksmt-core/build/release/**/ksmt-core-*.jar
            ksmt-z3/build/release/**/ksmt-z3-*.jar
            ksmt-bitwuzla/build/release/**/ksmt-bitwuzla-*.jar
            
