name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
          cache: gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build artifacts
        run: >
            ./gradlew
            publishAggregationToCentralPortal
            --no-daemon
            -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=2G
            -PmavenDeployUser=${{ secrets.MAVEN_CENTRAL_USER }}
            -PmavenDeployPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
            -PmavenSignGpgKey="${{ secrets.MAVEN_SIGN_GPG_KEY }}"
            -PmavenSignGpgPassword=${{ secrets.MAVEN_SIGN_GPG_PASSWORD }}

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./**/build/release/**/ksmt-*.jar
