name: Build and run long MaxSMT tests

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: Commit SHA
        required: false
        type: string
        default: ""

env:
  TEST_DATA_REVISION: 0.0.0

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      logics-matrix: ${{ steps.set-matrix.outputs.maxsmt-tests-matrix }}
    steps:
      - name: Print environment variables
        run: printenv

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check out ${{ github.event.inputs.commitSHA }} commit
        if: github.event.inputs.commitSHA != ''
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git fetch
          git checkout ${{ github.event.inputs.commitSHA }}

      - id: set-matrix
        name: Read and print config from maxsmt-tests-matrix.json
        run: |
          MAXSMT_TESTS=$(echo $(cat .github/workflows/maxsmt-tests-matrix.json))
          echo "maxsmt-tests-matrix=$MAXSMT_TESTS" >> $GITHUB_OUTPUT
          echo $MAXSMT_TESTS

  run-maxsmt-tests:
    needs: prepare-matrix
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.logics-matrix) }}

    name: Run ${{ matrix.NAME }} tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check out ${{ github.event.inputs.commitSHA }} commit
        if: github.event.inputs.commitSHA != ''
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git fetch
          git checkout ${{ github.event.inputs.commitSHA }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Download ${{ matrix.logics.NAME }} tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-maxsat-test:maxSmtBenchmark-${{ matrix.logics.NAME }}
            --no-daemon
            -PmaxSmtTestDataRevision=${{ env.TEST_DATA_REVISION }}

      - name: Run ${{ matrix.logics.NAME }} tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-maxsat-test:test
            --no-daemon
            --tests "io.ksmt.solver.maxsat.test.smt.KPMResSMTBenchmarkTest.maxSMTTest"

      - name: Archive ${{ matrix.logics.NAME }} test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.logics.NAME }}_test_report
          path: ksmt-maxsat-test/build/reports/tests/test/*
