name: Build and run long MaxSMT tests

on:
  workflow_dispatch:
    inputs:
      solver:
        type: choice
        description: Chosen MaxSMT solver configuration
        options:
        - KPMRes
        - KPrimalDualMaxRes
      smtSolver:
        type: choice
        description: Chosen SMT solver
        options:
        - Z3
        - Bitwuzla
        - Cvc5
        - Yices
      commitSHA:
        description: Commit SHA
        required: false
        type: string
        default: ""

env:
  TEST_DATA_REVISION: 0.0.0
  PUSHGATEWAY_HOSTNAME: monitoring.utbot.org

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      logics-matrix: ${{ steps.set-matrix.outputs.maxsmt-tests-matrix }}
    steps:
      - name: Print environment variables
        run: printenv

      - name: Checkout repository
        uses: actions/checkout@v3

      - id: set-matrix
        name: Create and print MaxSMT logics matrix

        # Exclude LIA, LRA tests for Bitwuzla solver
        # Exclude FP tests for Yices solver
        run: |
          if ${{ github.event.inputs.smtSolver == 'Bitwuzla' }}
          then
            MAXSMT_TESTS=$(echo $(cat .github/workflows/maxsmt-tests-matrix.json | jq '{ "logics": [ .[] | select(.NAME | contains("LIA") or contains("LRA") | not) ] }'))
          elif ${{ github.event.inputs.smtSolver == 'Yices' }}
          then
            MAXSMT_TESTS=$(echo $(cat .github/workflows/maxsmt-tests-matrix.json | jq '{ "logics": [ .[] | select(.NAME | contains("FP") | not) ] }'))
          else
            MAXSMT_TESTS=$(echo $(cat .github/workflows/maxsmt-tests-matrix.json | jq '{ "logics": [ .[] ] }'))
          fi

          echo "maxsmt-tests-matrix=$MAXSMT_TESTS" >> $GITHUB_OUTPUT
          echo $MAXSMT_TESTS

  run-maxsmt-tests:
    needs: prepare-matrix
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare-matrix.outputs.logics-matrix) }}

    name: Run ${{ matrix.logics.NAME }} tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check out ${{ github.event.inputs.commitSHA }} commit
        if: github.event.inputs.commitSHA != ''
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git fetch
          git checkout ${{ github.event.inputs.commitSHA }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Run monitoring
        # secret uploaded using base64 encoding to have one-line output:
        # cat file | base64 -w 0
        continue-on-error: true
        run: |
          chmod +x ./scripts/monitoring.sh
          ./scripts/monitoring.sh "${PUSHGATEWAY_HOSTNAME}" "${{ secrets.PUSHGATEWAY_USER }}" "${{ secrets.PUSHGATEWAY_PASSWORD }}"
          echo "Please visit Grafana to check metrics: https://${PUSHGATEWAY_HOSTNAME}/d/rYdddlPWk/node-exporter-full?orgId=1&from=now-1h&to=now&var-service=github&var-instance=${GITHUB_RUN_ID}-${HOSTNAME}&refresh=1m"

      - name: Download ${{ matrix.logics.NAME }} tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-maxsmt-test:maxSmtBenchmark-${{ matrix.logics.NAME }}
            --no-daemon
            -PmaxSmtTestDataRevision=${{ env.TEST_DATA_REVISION }}

      - name: Run ${{ matrix.logics.NAME }} tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-maxsmt-test:test
            --no-daemon
            --tests "io.ksmt.solver.maxsmt.test.smt.${{ github.event.inputs.solver }}SMTBenchmarkTest.maxSMT${{ github.event.inputs.smtSolver }}Test"

      - name: Archive ${{ matrix.logics.NAME }} test report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.logics.NAME }}_${{ github.event.inputs.solver }}_${{ github.event.inputs.smtSolver }}_test_report
          path: ksmt-maxsmt-test/build/reports/tests/test/*
